allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.getLayout().setBuildDirectory('../build')

subprojects {
    project.getLayout().setBuildDirectory("${rootProject.getLayout().getBuildDirectory()}/${project.name}")
}

subprojects {
    project.evaluationDependsOn(':app')

    // Fix Java 17 / Kotlin 1.9.22 compatibility
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions.jvmTarget = "21"
    }
}

tasks.register("clean", Delete) {
    delete rootProject.getLayout().getBuildDirectory()
}
